name: empman
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  fluentui_system_icons: ^1.1.220
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  sliding_clipped_nav_bar: ^3.1.0+4

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/logo/empman_logo.png"
  min_sdk_android: 21
  windows:
    generate: true
